# Generated by Django 4.1.3 on 2022-12-27 20:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=200)),
                ('category_decide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_sub_category_name', models.CharField(max_length=200)),
                ('sub_category_decide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_Name', models.CharField(max_length=200)),
                ('teacher_Name', models.CharField(max_length=200)),
                ('course_Image', models.ImageField(upload_to='course_Images')),
                ('fee', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('course_information', ckeditor.fields.RichTextField()),
                ('model_Name', models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical')], default='Online', max_length=10)),
                ('duration_In_Month', models.CharField(max_length=2)),
                ('Tags', models.CharField(max_length=200)),
                ('Description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('category_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
                ('sub_category_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sub_category')),
                ('sub_sub_category_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sub_sub_category')),
            ],
            options={
                'db_table': 'app_Course',
            },
        ),
        migrations.CreateModel(
            name='Additional_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', ckeditor.fields.RichTextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
            ],
        ),
    ]
